/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Iracheta95 (https://sketchfab.com/Iracheta95)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/el-principito-escena-3-bf4e7a9553434df5958aae6696a7f5b7
Title: El Principito - Escena 3
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import Prince from "../../assets/3d/el-principito.glb";

const PrinceModel = (props) => {
  const { nodes, materials } = useGLTF(Prince)
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.026, -4.415, 2.866]}
        rotation={[-0.06, 0, 0]}
        scale={[12.223, 7.475, 9.881]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Grass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.Dirt}
        />
      </group>
      <group position={[-6.945, -6.264, -13.336]} rotation={[0, 0.019, 0]} scale={0.382}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.Duck}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-10.538, -6.255, -13.432]} rotation={[0, 0.449, 0]} scale={0.245}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials['Duck.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[0.434, 0.958, -11.161]} rotation={[-2.963, 0.041, -Math.PI]} scale={2.27}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_72.geometry}
          material={materials['Material.007']}
          skeleton={nodes.Object_72.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_73.geometry}
          material={materials.Sueter}
          skeleton={nodes.Object_73.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_74.geometry}
          material={materials.Pantalones}
          skeleton={nodes.Object_74.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_75.geometry}
          material={materials.Bufanda}
          skeleton={nodes.Object_75.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_76.geometry}
          material={materials.Botas}
          skeleton={nodes.Object_76.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_77.geometry}
          material={materials.Cabello}
          skeleton={nodes.Object_77.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_78.geometry}
          material={materials.Ojos}
          skeleton={nodes.Object_78.skeleton}
        />
      </group>
      <group position={[-3.986, 2.967, -7.055]} rotation={[1.613, 0.018, -2.742]} scale={0.551}>
        <primitive object={nodes.GLTF_created_1_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_104.geometry}
          material={materials['Skin.001']}
          skeleton={nodes.Object_104.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_105.geometry}
          material={materials['White_furr.001']}
          skeleton={nodes.Object_105.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_106.geometry}
          material={materials['Feets.001']}
          skeleton={nodes.Object_106.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_107.geometry}
          material={materials['Material.008']}
          skeleton={nodes.Object_107.skeleton}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Tree}
        position={[5.462, 1.788, 1.201]}
        rotation={[-0.028, 0.004, -0.076]}
        scale={1.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Leafs}
        position={[3.436, 15.159, -1.159]}
        rotation={[-2.62, 1.492, 2.551]}
        scale={[4.488, 2.88, 2.416]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Leafs}
        position={[9.526, 10.483, 3.178]}
        rotation={[0.124, 0.319, -0.237]}
        scale={[2.322, 1.333, 1.211]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials['Material.001']}
        position={[0, -8.021, 0]}
        scale={[22.173, 1.045, 22.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Grass}
        position={[-3.414, 1.008, -4.521]}
        rotation={[-0.002, -0.001, 0.003]}
        scale={0.421}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Rock}
        position={[1.999, 1.058, 0.815]}
        scale={0.735}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Rock}
        position={[-10.152, 0.608, 4.707]}
        rotation={[0.003, 0.029, 0.329]}
        scale={0.724}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.Rock}
        position={[-10.231, -0.252, 1.877]}
        rotation={[-3.09, -0.289, -0.256]}
        scale={1.727}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.Rock}
        position={[4.681, -1.027, 11.708]}
        rotation={[-2.639, 0.045, 0.346]}
        scale={0.724}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.Rock}
        position={[4.707, -1.638, 12.119]}
        rotation={[2.752, 0.127, 0.346]}
        scale={0.479}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.Rock}
        position={[7.083, 0.289, 5.14]}
        rotation={[2.995, 0.127, 0.346]}
        scale={[0.654, 0.506, 0.668]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.Grass}
        position={[4.351, 1.308, 3]}
        rotation={[-0.002, -0.001, 0.003]}
        scale={0.575}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.Grass}
        position={[5.093, 1.5, -2.161]}
        rotation={[-3.138, -0.896, -3.135]}
        scale={0.943}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials.Grass}
        position={[3.829, 1.028, -2.301]}
        rotation={[-0.002, -0.001, 0.144]}
        scale={0.684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.Grass}
        position={[-9.103, 0.465, 3.451]}
        rotation={[-0.006, 1.169, 0.009]}
        scale={0.374}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials.Grass}
        position={[-11.028, 0.269, 0.727]}
        rotation={[2.542, -0.919, 2.911]}
        scale={0.672}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.Grass}
        position={[-10.567, -2.042, 12.012]}
        rotation={[0.132, 0.037, 0.149]}
        scale={0.62}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Grass}
        position={[5.663, -4.325, 17.02]}
        rotation={[-0.091, -0.023, -0.232]}
        scale={0.984}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.Grass}
        position={[3.961, -4.326, 18.21]}
        rotation={[-2.887, 0.957, -2.798]}
        scale={0.448}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.Rock}
        position={[-7.213, -6.213, 18.267]}
        rotation={[0.449, -0.622, 0.384]}
        scale={[0.485, 0.375, 0.495]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.Rock}
        position={[-11.4, -4.924, 14.245]}
        rotation={[0.368, -0.804, 0.081]}
        scale={[0.694, 0.537, 0.708]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.Rock}
        position={[1.223, -0.204, 6.623]}
        rotation={[0.247, -0.689, 0.018]}
        scale={[0.466, 0.245, 0.458]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials.Grass}
        position={[-5.508, 0.102, 7.335]}
        rotation={[-3.098, -0.044, -3.136]}
        scale={0.434}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.Grass}
        position={[12.403, -0.578, 0.521]}
        rotation={[3.014, 0.241, -2.496]}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials['Material.003']}
        position={[-7.152, 23.172, -10.731]}
        rotation={[-2.42, 1.462, 2.431]}
        scale={[1.527, 1.126, 1.282]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_57.geometry}
        material={materials.material_0}
        position={[-10.789, 11.604, -10.772]}
        rotation={[-0.417, 1.232, 0.468]}
        scale={0.579}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials.material_0}
        position={[19.597, 10.246, 9.008]}
        rotation={[0, -1.428, 0]}
        scale={0.798}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_61.geometry}
        material={materials['Material.002']}
        position={[-0.029, -7.047, -0.107]}
        scale={13.185}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.Leafs}
        position={[-3.634, -1.013, 12.851]}
        rotation={[-0.216, 0.493, 0.182]}
        scale={[1.824, 1.612, 1.424]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials.Leafs}
        position={[-6.123, -0.634, 10.803]}
        rotation={[-3.113, -0.902, -0.297]}
        scale={[1.313, 1.098, 1.01]}
      />
    </group>
  )
}

useGLTF.preload('/el_principito_-_escena_3.glb')
export default PrinceModel;